fix: Remove "Integration Tests" stage from opbeansPipeline (#1903)
* fix: Remove "Integration Tests" stage from opbeansPipeline

opbeans-$lang Jenkins builds are currently failing on the "Integration Tests"
step with:
    Failed to trigger build of apm-integration-tests-selector-mbp/main
They all run the `opbeansPipeline()` that is defined here.

https://github.com/elastic/apm-integration-testing/pull/1524 removed
the integration tests from apm-integration-testing.git and its Jenkinsfile.

* attempted fix for test failures in GitHub CI "build" check

   Error:  Failures:
      Error:    OpbeansPipelineStepTests.test_when_main_branch:45
      Error:    OpbeansPipelineStepTests.test_when_main_branch_and_empty_downstreamJobs:54

I'm guessing that the references to the
"apm-integration-tests-selector-mbp/main" job are no longer relevant
given we are removing that stage.