attempted fix for test failures in GitHub CI "build" check
   Error:  Failures:
      Error:    OpbeansPipelineStepTests.test_when_main_branch:45
      Error:    OpbeansPipelineStepTests.test_when_main_branch_and_empty_downstreamJobs:54

I'm guessing that the references to the
"apm-integration-tests-selector-mbp/main" job are no longer relevant
given we are removing that stage.